export enum TipoAccionUsuario {
    // Documentos
    VALIDACION_DOCUMENTO = 'VALIDACION_DOCUMENTO',
    SUBIDA_DOCUMENTO_IDENTIDAD = 'SUBIDA_DOCUMENTO_IDENTIDAD',
    RESUBIDA_DOCUMENTO_IDENTIDAD = 'RESUBIDA_DOCUMENTO_IDENTIDAD',
    SUBIDA_LICENCIA_CONDUCIR = 'SUBIDA_LICENCIA_CONDUCIR',
    RESUBIDA_LICENCIA_CONDUCIR = 'RESUBIDA_LICENCIA_CONDUCIR',
    SUBIDA_SEGURO = 'SUBIDA_SEGURO',
    RESUBIDA_SEGURO = 'RESUBIDA_SEGURO',
    SUBIDA_CEDULA = 'SUBIDA_CEDULA',
    RESUBIDA_CEDULA = 'RESUBIDA_CEDULA',
    
    // Registro y Perfil
    REGISTRO_USUARIO = 'REGISTRO_USUARIO',
    REGISTRO_CONDUCTOR = 'REGISTRO_CONDUCTOR',
    ACTUALIZACION_PERFIL = 'ACTUALIZACION_PERFIL',
    ACTUALIZACION_CONTRASENA = 'ACTUALIZACION_CONTRASENA',
    ACTUALIZACION_FOTO_PERFIL = 'ACTUALIZACION_FOTO_PERFIL',
    
    // Vehículos
    REGISTRO_VEHICULO = 'REGISTRO_VEHICULO',
    ACTUALIZACION_VEHICULO = 'ACTUALIZACION_VEHICULO',
    
    // Viajes
    CREACION_VIAJE = 'CREACION_VIAJE',
    CANCELACION_VIAJE = 'CANCELACION_VIAJE',
    MODIFICACION_VIAJE = 'MODIFICACION_VIAJE',
    
    // Admin
    VERIFICACION_DOCUMENTO = 'VERIFICACION_DOCUMENTO',
    RECHAZO_DOCUMENTO = 'RECHAZO_DOCUMENTO'
  }