export enum TipoAccionUsuario {
    // Documentos
    VALIDACION_DOCUMENTO = 'VALIDACION_DOCUMENTO',
    SUBIDA_DOCUMENTO_IDENTIDAD = 'SUBIDA_DOCUMENTO_IDENTIDAD',
    RESUBIDA_DOCUMENTO_IDENTIDAD = 'RESUBIDA_DOCUMENTO_IDENTIDAD',
    SUBIDA_LICENCIA_CONDUCIR = 'SUBIDA_LICENCIA_CONDUCIR',
    RESUBIDA_LICENCIA_CONDUCIR = 'RESUBIDA_LICENCIA_CONDUCIR',
    SUBIDA_SEGURO = 'SUBIDA_SEGURO',
    RESUBIDA_SEGURO = 'RESUBIDA_SEGURO',
    SUBIDA_CEDULA = 'SUBIDA_CEDULA',
    RESUBIDA_CEDULA = 'RESUBIDA_CEDULA',

     // Authentication
     INICIO_SESION = 'INICIO_SESION',
     CIERRE_SESION = 'CIERRE_SESION',
     VERIFICACION_EMAIL = 'VERIFICACION_EMAIL',
     SOLICITUD_RESET_PASSWORD = 'SOLICITUD_RESET_PASSWORD',
     RESET_PASSWORD = 'RESET_PASSWORD',
     LOGIN_SOCIAL = 'LOGIN_SOCIAL',
    
    // Registro y Perfil
    REGISTRO_USUARIO = 'REGISTRO_USUARIO',
    REGISTRO_CONDUCTOR = 'REGISTRO_CONDUCTOR',
    ACTUALIZACION_PERFIL = 'ACTUALIZACION_PERFIL',
    ACTUALIZACION_CONTRASENA = 'ACTUALIZACION_CONTRASENA',
    ACTUALIZACION_FOTO_PERFIL = 'ACTUALIZACION_FOTO_PERFIL',
    
    // Vehículos
    REGISTRO_VEHICULO = 'REGISTRO_VEHICULO',
    ACTUALIZACION_VEHICULO = 'ACTUALIZACION_VEHICULO',
    
    // Viajes
    CREACION_VIAJE = 'CREACION_VIAJE',
    CANCELACION_VIAJE = 'CANCELACION_VIAJE',
    MODIFICACION_VIAJE = 'MODIFICACION_VIAJE',
    FINALIZACION_VIAJE = 'FINALIZACION_VIAJE',
    RECHAZO_RESERVACION_PENDIENTE = 'RECHAZO_RESERVACION_PENDIENTE',
    
    // Admin
    VERIFICACION_DOCUMENTO = 'VERIFICACION_DOCUMENTO',
    RECHAZO_DOCUMENTO = 'RECHAZO_DOCUMENTO',

      // Notification related actions
  SUSCRIPCION_NOTIFICACIONES = 'SUSCRIPCION_NOTIFICACIONES',
  CANCELACION_SUSCRIPCION_NOTIFICACIONES = 'CANCELACION_SUSCRIPCION_NOTIFICACIONES',
  ENVIO_NOTIFICACION = 'ENVIO_NOTIFICACION',
  NOTIFICACION_TIEMPO_REAL = 'NOTIFICACION_TIEMPO_REAL',
  GET_NOTIFICATIONS = 'GET_NOTIFICATIONS',
  CREATE_NOTIFICATION = 'CREATE_NOTIFICATION',
  MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ',
  MARK_ALL_NOTIFICATIONS_READ = 'MARK_ALL_NOTIFICATIONS_READ',
  CLEAR_ALL_NOTIFICATIONS = 'CLEAR_ALL_NOTIFICATIONS',
  SUPPORT_TICKET_RESOLVED = 'SUPPORT_TICKET_RESOLVED',
  }